project:
  type: website

resources:
  - resources/predtimechart.js
  - resources/predevals_interface.js

website:
  title: "Hubverse Dashboard Template"
  repo-url: https://github.com/hubverse-org/hub-dashboard-template
  repo-actions: [edit, source, issue]
  repo-subdir: pages
  navbar:
    left:
      - icon: house
        href: index.qmd
      - text: "Forecasts"
        icon: graph-up
        href: forecast.qmd
      - text: "Evaluation"
        icon: table
        href: eval.qmd
    right:
      - text: "Hub"
        icon: database
        href: https://github.com/cdcepi/FluSight-forecast-hub
  page-footer:
    right:
      - text: "Built with the hubverse dashboard"
        href: https://hubverse.io/en/latest/user-guide/dashboards.html
format:
  html:
    from: markdown+emoji
    lang: en-US
    toc: false
    theme: yeti
    link-external-icon: true
    anchor-sections: true
    css: resources/css/styles.css
    include-in-header: resources/header.html
    include-after-body: resources/blank.html



