name: Create and publish a Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths:
      - render.sh
      - modify-quarto-yml.sh
      - static/**
      - Dockerfile
      - entrypoint.sh
  workflow_dispatch:

permissions: read-all
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2
      - id: setup-buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 #v3.10.0 
      - id: container-login
        if: ${{ github.event_name == "push" }}
        name: Log in to the Container registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        if: ${{ github.event_name == "push" }}
        name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 #v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - id: build
        name: Build and export
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 #v6.15.0
        with:
          context: .
          file: ./Dockerfile
          tags: name/app:latest
          outputs: type=oci,dest=/tmp/image.tar
      - id: upload
        name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: /tmp/image.tar
